name: Setup spiced
description: 'composite action'

# Downloads the most recent spiced build from MinIO, within the last 10 commits
#
# Requires the MinIO CLI to be installed and configured to use this action
inputs:
  spiced_commit: # optionally override the commit to download
    description: 'spiced build commit'
    required: false
    type: string
outputs:
  spiced_commit:
    value: ${{ steps.output_spiced_commit.outputs.spiced_commit }}
runs:
  using: 'composite'
  steps:
    - name: Find the latest built spiced commit
      if: ${{ !inputs.spiced_commit }}
      shell: bash
      run: |
        git fetch --depth=10 origin trunk
        commit_hashes=($(git log origin/trunk --pretty=format:"%H" -n 10))

        for hash in "${commit_hashes[@]}"; do
          echo "Checking $hash in MinIO"
          if mc stat spice-minio/artifacts/spiced/linux-x86_64/$hash/spiced_models_linux_x86_64.tar.gz; then
            echo "Found $hash in MinIO"
            echo "SPICED_COMMIT=$hash" >> $GITHUB_ENV
            exit 0
          fi
        done

        echo "Could not find any recently built spiced commit in MinIO"
        exit 1
    
    - name: Set SPICED_COMMIT from workflow input
      shell: bash
      if: ${{ inputs.spiced_commit }}
      run: |
        echo "SPICED_COMMIT=${{ inputs.spiced_commit }}" >> $GITHUB_ENV
    
    - name: Output SPICED_COMMIT
      id: output_spiced_commit
      shell: bash
      run: echo "SPICED_COMMIT=$SPICED_COMMIT" >> $GITHUB_OUTPUT

    - name: Download spiced from MinIO
      shell: bash
      run: |
        mc cp spice-minio/artifacts/spiced/linux-x86_64/$SPICED_COMMIT/spiced_models_linux_x86_64.tar.gz spiced_models_linux_x86_64.tar.gz
        tar -xzf spiced_models_linux_x86_64.tar.gz
        sudo cp ./spiced /usr/local/bin/spiced