[package]
description = "Spice OSS"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "spiced"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
app = { path = "../../crates/app" }
clap = { workspace = true, features = ["derive"] }
flightrepl = { path = "../../crates/flightrepl" }
futures.workspace = true
opentelemetry.workspace = true
opentelemetry-http.workspace = true
opentelemetry-prometheus.workspace = true
opentelemetry-zipkin.workspace = true
opentelemetry_sdk.workspace = true
otel-arrow = { path = "../../crates/otel-arrow" }
prometheus.workspace = true
reqwest.workspace = true
runtime = { path = "../../crates/runtime" }
runtime-auth = { path = "../../crates/runtime-auth" }
rustls.workspace = true
rustls-pemfile.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
snafu.workspace = true
snmalloc-rs = "0.3.6"
spice-cloud = { path = "../../crates/spice_cloud" }
telemetry = { path = "../../crates/telemetry" }
tokio.workspace = true
tpc-extension = { path = "../../crates/tpc_extension", optional = true }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true

# Non-default features should be added to `lint-rust` make target.
[features]
anonymous_telemetry = ["telemetry/anonymous_telemetry"]
aws-secrets-manager = ["runtime/aws-secrets-manager"]
clickhouse = ["runtime/clickhouse"]
cuda = ["runtime/cuda"]
databricks = ["runtime/databricks"]
debezium = ["runtime/debezium"]
default = [
  "duckdb",
  "postgres",
  "sqlite",
  "mysql",
  "flightsql",
  "delta_lake",
  "databricks",
  "dremio",
  "clickhouse",
  "sharepoint",
  "snowflake",
  "spark",
  "ftp",
  "debezium",
  "anonymous_telemetry",
  "mssql",
  "dynamodb",
  "imap",
]
delta_lake = ["runtime/delta_lake"]
dev = ["runtime/dev"]
dremio = ["runtime/dremio"]
duckdb = ["runtime/duckdb"]
dynamodb = ["runtime/dynamodb"]
flightsql = ["runtime/flightsql"]
ftp = ["runtime/ftp"]
imap = ["runtime/imap"]
keyring-secret-store = ["runtime/keyring-secret-store"]
mcp = ["runtime/mcp"]
metal = ["runtime/metal"]
models = ["runtime/models"]
mssql = ["runtime/mssql"]
mysql = ["runtime/mysql"]
odbc = ["runtime/odbc"]
postgres = ["runtime/postgres"]
postgres-write = ["runtime/postgres-write"]
release = []
sharepoint = ["runtime/sharepoint"]
snowflake = ["runtime/snowflake"]
spark = ["runtime/spark"]
sqlite = ["runtime/sqlite"]
tpc-extension = ["dep:tpc-extension"]
