[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
name = "arrow_tools"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow.workspace = true
arrow-cast.workspace = true
arrow-schema.workspace = true
snafu.workspace = true
datafusion.workspace = true
